language: node_js
node_js:
- '12'
- '14'
deploy:
  api_key:
    secure: F6Q2Sjmd3l5fU+Bb6+EnhnqFjMQjl8xyVIrJcg8I/KBhGBNTigJYnDKQ0iaDzslNPNMiOZ5OITtXLDaPHduNh5+I8BuTe0GagbQ1E97K70WAEEzc/EUbXTnbRNtXpF447+xVdRSjWWX7KCgQ5GjNggcyhD6neTSEE854ue1TEdPfUO8Ju2Dygw0K/30Z5cyM+f3fVot+FRcTUeiP8lk+ouK76E1/LRynNGsrVPMHxakanA/vf4erZmZHdyyyFXANJBAmKKaOV46uqximZrPzZQ6L2XelccXkQfzFoYaOVPDCK/2IAyz2Vj+gbtnUxgwXNZoV4Ea7TDCcs5g9I6bHl5t2WaNrZKurTb7SVSrVdCwuoDsHuv9YnQRIAFRQMTD8n4q3Pd38I9rdLmi/eFSodZYoCIqSZiVqd9REANRweHlmkEWvofu6bo7dGN1SXn2FrVQJfYfFyG5AroPSffRyMc4OqNea7KzCx2BEjrUtqdLnmsdUI3JiHk1lSZ3INN57fCM7J71TeLUN45SX7FVyqstrjnKV2TBc+f2RQ4mwNkry3ofMdzclG24gqeOQy4DXZzkcILjP54I5mTGHeNpABD8ZNV61e+Yjk5bevcaswwt4Vtn5KS1+Bwp0pxhVGhkc59IlVkgGw409PelXH6cHQAJ+h4zhhVh33I+P3K3OjDQ=
  email: julian@dotcore.co.il
  provider: npm
  skip_cleanup: true # prevent having to rebuild all files
  on:
    tags: true
after_script:
- npm run coveralls
services:
- redis-server
